# Generated by Django 4.1.1 on 2023-05-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Post', '0002_posts_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
    ]
