# Generated by Django 4.2.1 on 2023-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('session', models.CharField(max_length=50)),
                ('hall', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('permanent_address', models.CharField(max_length=200)),
            ],
        ),
    ]
